on:
  push:
    branches:
      - develop
name: Zip resources
jobs:
  publish:
    name: zip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: |
          *.html
          css
          icons
          js
          manifest.json
