on:
  push:
    branches:
      - master
name: Zip resources
jobs:
  publish:
    name: zip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: |
          *.html
          css
          icons
          js
          manifest.json
